version: "3.9"

services:
  db:
    image: redas8080/postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: redas8080/dockpushtest-backend:latest
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: redas8080/dockpushtest-frontend:latest
    environment:
      - CI=true
    expose:
      - "3000"
    stdin_open: true
    restart: always

  nginx:
    image: redas8080/nginx-backend:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
