# Generated by Django 5.2.1 on 2025-05-25 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_delete_gameroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('has_ship', models.BooleanField(default=False)),
                ('is_shot', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_field', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('has_ship', models.BooleanField(default=False)),
                ('is_shot', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_field', to='game.room')),
            ],
        ),
    ]
