# Generated by Django 5.2.1 on 2025-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_botfield_playerfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
