# Generated by Django 5.2.1 on 2025-05-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='GameRoom', max_length=100),
        ),
    ]
