# Generated by Django 5.2.1 on 2025-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfield',
            name='is_mis_shot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerfield',
            name='is_mis_shot',
            field=models.BooleanField(default=False),
        ),
    ]
