# Generated by Django 5.2.1 on 2025-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_botfield_is_mis_shot_playerfield_is_mis_shot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='turn',
        ),
        migrations.AddField(
            model_name='room',
            name='turn_count',
            field=models.IntegerField(default=0),
        ),
    ]
