# Generated by Django 5.2.1 on 2025-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_room_turn_room_turn_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
