# Generated by Django 5.2.1 on 2025-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_room_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='turn_count',
        ),
        migrations.AlterField(
            model_name='room',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
