# Generated by Django 5.2.1 on 2025-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_room_turn_count_alter_room_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfield',
            name='is_game_over',
            field=models.BooleanField(default=False),
        ),
    ]
