# Generated by Django 5.2.1 on 2025-05-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_playerfield_is_game_over_playerfield_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerfield',
            name='player',
        ),
    ]
